#!/usr/bin/env python3
"""
Generate music_data.h from captured engine state.

Reads tmp/music_state.txt and produces compact note sequences
for the GBC remake's music player.
"""

import math


NOTES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']


def freq_to_note(gb_freq):
    if gb_freq >= 2048 or gb_freq <= 0:
        return '---'
    hz = 131072.0 / (2048 - gb_freq)
    midi = 69 + 12 * math.log2(hz / 440.0)
    return f'{NOTES[round(midi) % 12]}{(round(midi) // 12) - 1}'


def parse_and_extract(path):
    """Parse state file and extract note events per channel."""
    with open(path) as f:
        lines = f.readlines()[1:]

    ch_data = {'ch1': [], 'ch2': [], 'ch3': []}
    prev = {'ch1': -1, 'ch2': -1, 'ch3': -1}

    for line in lines:
        parts = line.strip().split('|')
        if len(parts) < 5:
            continue
        frame = int(parts[0].strip())

        for idx, ch_name in enumerate(['ch1', 'ch2', 'ch3']):
            ch = parts[idx + 1].strip().split()
            freq = int(ch[1], 16) | (int(ch[2], 16) << 8)
            vol = int(ch[3], 16)
            pan = int(ch[5], 16)

            if freq != prev[ch_name]:
                ch_data[ch_name].append({
                    'frame': frame, 'freq': freq, 'vol': vol, 'pan': pan
                })
                prev[ch_name] = freq

    # Calculate durations
    for ch_name in ch_data:
        events = ch_data[ch_name]
        for i in range(len(events) - 1):
            events[i]['duration'] = events[i + 1]['frame'] - events[i]['frame']
        if events:
            events[-1]['duration'] = 16

    return ch_data


def find_loop(events, min_period=10):
    """Find loop period in note events."""
    freqs = [e['freq'] for e in events]
    for period in range(min_period, len(freqs) // 2):
        if all(freqs[i] == freqs[i + period]
               for i in range(period) if i + period < len(freqs)):
            return period
    return len(events)


def main():
    ch_data = parse_and_extract('tmp/music_state.txt')

    # Find loops
    loops = {}
    for ch in ['ch1', 'ch2', 'ch3']:
        loops[ch] = find_loop(ch_data[ch])
        print(f"{ch}: {len(ch_data[ch])} events, loop={loops[ch]}")

    # Use one full loop cycle for each channel
    # Ch1: 17 events (loop at 17 means 0-16 is one cycle)
    # But the long F5 sustain (event 15, 500 frames) needs special handling
    # Split it into multiple shorter events for smoother playback

    ch1 = ch_data['ch1'][:loops['ch1']]
    ch2 = ch_data['ch2'][:loops['ch2']]
    ch3 = ch_data['ch3'][:loops['ch3']]

    # Handle the long sustain in Ch1 by splitting into 16-frame chunks
    # Event 15 is F5 with 500-frame duration - split into repeated notes
    ch1_expanded = []
    for e in ch1:
        if e['duration'] > 64:
            # Split long notes into 16-frame chunks
            remaining = e['duration']
            while remaining > 0:
                chunk = min(remaining, 16)
                ch1_expanded.append({
                    'freq': e['freq'], 'vol': e['vol'],
                    'pan': e['pan'], 'duration': chunk
                })
                remaining -= chunk
        else:
            ch1_expanded.append(e)

    print(f"\nAfter expanding Ch1 sustains: {len(ch1_expanded)} events")
    print(f"Ch2: {len(ch2)} events")
    print(f"Ch3: {len(ch3)} events")

    # Calculate total data size
    # Per event: 2 bytes freq + 1 byte duration = 3 bytes
    total_bytes = (len(ch1_expanded) + len(ch2) + len(ch3)) * 3
    print(f"Total music data: {total_bytes} bytes")

    # Generate C header
    lines = []
    lines.append("// AUTO-GENERATED by scripts/generate_music_data.py")
    lines.append("// Music data extracted from Penta Dragon (J) ROM - Level 1 BGM")
    lines.append("// 3 channels: Ch1=square melody, Ch2=square harmony, Ch3=wave bass")
    lines.append("")
    lines.append("#ifndef __MUSIC_DATA_H__")
    lines.append("#define __MUSIC_DATA_H__")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")

    # Note event structure
    lines.append("// Note event: frequency (GB 11-bit), duration in frames")
    lines.append("typedef struct {")
    lines.append("    uint16_t freq;   // GB frequency register value (11-bit)")
    lines.append("    uint8_t  dur;    // Duration in frames (1-255)")
    lines.append("} note_event_t;")
    lines.append("")

    # Generate each channel
    for name, events, label in [
        ('ch1', ch1_expanded, 'melody (square 1)'),
        ('ch2', ch2, 'harmony (square 2)'),
        ('ch3', ch3, 'bass (wave)')
    ]:
        lines.append(f"// {label}: {len(events)} events")
        lines.append(f"#define MUSIC_{name.upper()}_LEN {len(events)}")
        lines.append(f"static const note_event_t music_{name}[{len(events)}] = {{")

        row = []
        for i, e in enumerate(events):
            note = freq_to_note(e['freq'])
            dur = min(e['duration'], 255)
            row.append(f"{{0x{e['freq']:04X},{dur:3d}}}")
            if len(row) == 4 or i == len(events) - 1:
                comment = ""
                if len(row) <= 4:
                    notes_str = " ".join(freq_to_note(events[i - len(row) + 1 + j]['freq'])
                                         for j in range(len(row)))
                    comment = f"  // {notes_str}"
                lines.append("    " + ", ".join(row) + "," + comment)
                row = []

        lines.append("};")
        lines.append("")

    # Envelope and duty settings (extracted from capture)
    lines.append("// Channel settings (from original engine state)")
    lines.append("#define MUSIC_CH1_SWEEP  0x08  // NR10: no sweep")
    lines.append("#define MUSIC_CH1_DUTY   0x80  // NR11: 50% duty")
    lines.append("#define MUSIC_CH1_ENV    0x77  // NR12: vol=7, increase, period=7")
    lines.append("#define MUSIC_CH2_DUTY   0x40  // NR21: 25% duty")
    lines.append("#define MUSIC_CH2_ENV    0x67  // NR22: vol=6, increase, period=7")
    lines.append("#define MUSIC_CH3_ONOFF  0xFF  // NR30: wave on")
    lines.append("#define MUSIC_CH3_VOL    0xDF  // NR32: 50% volume")
    lines.append("")

    # Wave RAM (triangle waveform from original)
    lines.append("// Wave RAM pattern (triangle-ish, from original)")
    lines.append("static const uint8_t music_wave[16] = {")
    lines.append("    0xFF, 0xED, 0xCB, 0xAA, 0xAA, 0xBC, 0xDE, 0xFF,")
    lines.append("    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,")
    lines.append("};")
    lines.append("")

    # Master volume
    lines.append("// Master volume and panning")
    lines.append("#define MUSIC_MASTER_VOL  0x77  // NR50: max volume both sides")
    lines.append("#define MUSIC_PANNING     0xFF  // NR51: all channels both speakers")
    lines.append("")
    lines.append("#endif /* __MUSIC_DATA_H__ */")

    output = "\n".join(lines)
    with open('src/music_data.h', 'w') as f:
        f.write(output)

    print(f"\nWrote src/music_data.h ({len(output)} bytes)")

    # Print verification
    print("\n=== Ch1 Melody (expanded) ===")
    for e in ch1_expanded:
        print(f"  {freq_to_note(e['freq']):4s} dur={e['duration']:3d}f")

    print(f"\n=== Ch2 Harmony (first 20) ===")
    for e in ch2[:20]:
        print(f"  {freq_to_note(e['freq']):4s} dur={e['duration']:3d}f")

    print(f"\n=== Ch3 Bass (first 20) ===")
    for e in ch3[:20]:
        print(f"  {freq_to_note(e['freq']):4s} dur={e['duration']:3d}f")


if __name__ == '__main__':
    main()
