// AUTO-GENERATED by scripts/generate_music_data.py
// Music data extracted from Penta Dragon (J) ROM - Level 1 BGM
// 3 channels: Ch1=square melody, Ch2=square harmony, Ch3=wave bass
// Full loop: ~878 frames (~14.6 seconds)

#ifndef __MUSIC_DATA_H__
#define __MUSIC_DATA_H__

#include <stdint.h>

// Note event: frequency (GB 11-bit), duration in frames
typedef struct {
    uint16_t freq;   // GB frequency register value (11-bit)
    uint8_t  dur;    // Duration in frames (1-255)
} note_event_t;

// Special frequency value: rest (silence)
#define MUSIC_REST 0x0000

// melody (square 1): 18 events per loop
// A section: active melody (events 0-14)
// B section: sustained F5 drone (events 15-16, total ~500 frames)
// Pickup: A#5 → loops back to start
#define MUSIC_CH1_LEN 18
static const note_event_t music_ch1[MUSIC_CH1_LEN] = {
    {0x076B, 11},  //  0: A5   (pickup into melody)
    {0x0759, 25},  //  1: G5
    {0x076B, 12},  //  2: A5
    {0x0759, 24},  //  3: G5   (held)
    {0x0744, 37},  //  4: F5   (held)
    {0x072D, 36},  //  5: D#5  (held)
    {0x0714, 13},  //  6: C#5
    {0x0744, 12},  //  7: F5
    {0x0773, 12},  //  8: A#5
    {0x076B, 25},  //  9: A5
    {0x0759, 24},  // 10: G5   (held)
    {0x076B, 12},  // 11: A5
    {0x0759, 25},  // 12: G5   (held)
    {0x0744, 36},  // 13: F5   (held)
    {0x072D, 49},  // 14: D#5  (long held)
    {0x0744,255},  // 15: F5   (drone part 1)
    {0x0744,245},  // 16: F5   (drone part 2 — total ~500 frames)
    {0x0773, 13},  // 17: A#5  (pickup into loop)
};

// harmony (square 2): 50 events per loop
// Alternating octave pattern: high note → low note, creating arpeggio effect
// Two chord progressions: F major (A4-F3) and D#/Eb (G4-D#3)
#define MUSIC_CH2_LEN 50
static const note_event_t music_ch2[MUSIC_CH2_LEN] = {
    {0x06D6, 11}, {0x0511, 25}, {0x06D6, 12}, {0x0511, 24},  // A4 F3 A4 F3
    {0x06B2, 12}, {0x04B5, 25}, {0x06B2, 12}, {0x04B5, 24},  // G4 D#3 G4 D#3
    {0x06B2, 13}, {0x04B5, 12}, {0x0511, 24}, {0x06D6, 13},  // G4 D#3 F3 A4
    {0x0511, 24}, {0x06D6, 12}, {0x0511, 25}, {0x0689, 12},  // F3 A4 F3 F4
    {0x044E, 24}, {0x0689, 12}, {0x044E, 25}, {0x0689, 12},  // C#3 F4 C#3 F4
    {0x044E, 12}, {0x0511, 25}, {0x06D6, 12}, {0x0511, 24},  // C#3 F3 A4 F3
    {0x06D6, 12}, {0x0511, 25}, {0x06B2, 12}, {0x04B5, 24},  // A4 F3 G4 D#3
    {0x06B2, 13}, {0x04B5, 24}, {0x06B2, 12}, {0x04B5, 12},  // G4 D#3 G4 D#3
    {0x0511, 25}, {0x06D6, 12}, {0x0511, 24}, {0x06D6, 13},  // F3 A4 F3 A4
    {0x0511, 24}, {0x0689, 12}, {0x044E, 25}, {0x0689, 12},  // F3 F4 C#3 F4
    {0x044E, 24}, {0x0689, 13}, {0x044E, 12}, {0x0689, 12},  // C#3 F4 C#3 F4
    {0x044E, 24}, {0x0689, 13}, {0x044E, 24}, {0x0689, 12},  // C#3 F4 C#3 F4
    {0x044E, 12}, {0x0511, 25},                                // C#3 F3
};

// bass (wave): 56 events per loop
// Root note patterns with walking bass lines
// F minor / C# major alternation matching harmony
#define MUSIC_CH3_LEN 56
static const note_event_t music_ch3[MUSIC_CH3_LEN] = {
    {0x0689, 11}, {0x0511, 37}, {0x060B, 12}, {0x0689, 12},  // F4 F3 C4 F4
    {0x04B5, 12}, {0x05CE, 13}, {0x065B, 12}, {0x04B5, 24},  // D#3 A#3 D#4 D#3
    {0x05CE, 12}, {0x04B5, 13}, {0x065B, 12}, {0x0511, 12},  // A#3 D#3 D#4 F3
    {0x060B, 12}, {0x0689, 13}, {0x0511, 36}, {0x060B, 12},  // C4 F4 F3 C4
    {0x0689, 13}, {0x044E, 12}, {0x0589, 12}, {0x0627, 12},  // F4 C#3 G#3 C#4
    {0x044E, 37}, {0x0589, 12}, {0x0627, 12}, {0x0511, 12},  // C#3 G#3 C#4 F3
    {0x060B, 13}, {0x0689, 12}, {0x0511, 36}, {0x060B, 13},  // C4 F4 F3 C4
    {0x0689, 12}, {0x04B5, 12}, {0x05CE, 12}, {0x065B, 12},  // F4 D#3 A#3 D#4
    {0x04B5, 25}, {0x05CE, 12}, {0x04B5, 12}, {0x065B, 12},  // D#3 A#3 D#3 D#4
    {0x0511, 13}, {0x060B, 12}, {0x0689, 12}, {0x0511, 37},  // F3 C4 F4 F3
    {0x060B, 12}, {0x0689, 12}, {0x044E, 12}, {0x0589, 12},  // C4 F4 C#3 G#3
    {0x0627, 13}, {0x044E, 36}, {0x0589, 13}, {0x0627, 12},  // C#4 C#3 G#3 C#4
    {0x044E, 12}, {0x0589, 12}, {0x0627, 12}, {0x044E, 37},  // C#3 G#3 C#4 C#3
    {0x0589, 12}, {0x0627, 12}, {0x0511, 13}, {0x060B, 12},  // G#3 C#4 F3 C4
};

// Channel settings (from original engine state)
#define MUSIC_CH1_SWEEP  0x08  // NR10: no sweep
#define MUSIC_CH1_DUTY   0x80  // NR11: 50% duty
#define MUSIC_CH1_ENV    0x77  // NR12: vol=7, increase, period=7
#define MUSIC_CH2_DUTY   0x40  // NR21: 25% duty
#define MUSIC_CH2_ENV    0x67  // NR22: vol=6, increase, period=7
#define MUSIC_CH3_ONOFF  0xFF  // NR30: wave on
#define MUSIC_CH3_VOL    0xDF  // NR32: 50% volume

// Wave RAM pattern (triangle-ish, from original)
static const uint8_t music_wave[16] = {
    0xFF, 0xED, 0xCB, 0xAA, 0xAA, 0xBC, 0xDE, 0xFF,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

// Master volume and panning
#define MUSIC_MASTER_VOL  0x77  // NR50: max volume both sides
#define MUSIC_PANNING     0xFF  // NR51: all channels both speakers

#endif /* __MUSIC_DATA_H__ */
